config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'about' => 'static_pages#about'
  get 'signup' => 'users#new'
  get  'help' => 'static_pages#help'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token

	before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}

   # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

   # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  #Remember user token in the database
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end


  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  #Forger user
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email])
  	if user && user.authenticate(params[:session][:password])
  		log_in user
      params[:session][:remember_me]=='1'  ? remember(user): forget(user)
  		redirect_back_or user
  	else
  		flash.now[:dander] = 'Invalid password/email combinate'
  		render 'new'
  	end
  end

  def destroy
  	log_out if logged_in?
  	redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only:[:edit,:update]
  before_action :correct_user, only: [:edit,:update]
  def new
  	@user=User.new
  end

  def show
  	@user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])  
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile Update"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		#Succesfull create
      log_in @user
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

   private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    def logged_in_user 
        unless logged_in?
          store_location
          flash[:danger] = "Please log in"
          redirect_to login_url
        end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless correct_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	#Logs in the given user
	def log_in(user)
		session[:user_id]=user.id
	end

	#Forget session
	def forget(user)
		user.forget
		cookies.delete(:user_id)		
		cookies.delete(:remember_token)
	end
	# Remembers a user in a persistent session.
	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:remember_token] = user.remember_token
	end

	#Log out the current user
	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end
	# Returns the user corresponding to the remember token cookie.
	def current_user
	  if (user_id = session[:user_id])
	    @current_user ||= User.find_by(id: user_id)
	  elsif (user_id = cookies.signed[:user_id])
	    user = User.find_by(id: user_id)
	    if user && user.authenticated?(cookies[:remember_token])
	      log_in user
	      @current_user = user
	    end
	  end
	end

	def correct_user?(user)
		current_user == user
	end

	def logged_in?
		!current_user.nil?
	end

	def store_location
		session[:forwading_url] = request.url if request.get?
	end

	def redirect_back_or(default)
		redirect_to(session[:forwading_url] || default)
		session.delete(:forwading_url)		
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-inverse navbar-fixed-top">
	<div class="container">
		<%= link_to "BookLand", root_path, class: "navbar-brand" %>
		<form class="navbar-form navbar-left" role="search">
			<div class="form-group">
				<input class="form-control" type="text" placeholder="Search"></input>		
			</div>
			<button class="btn btn-default" type="submit">
				<%= image_tag "search_ic.png", alt:"Search" , id:"search_ic" %>
			</button>
		</form>
		
			  <ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Help", help_path %></li>
				<li><%= link_to "About", about_path %></li>			
			    <% if logged_in? %>
		          <li><%= link_to "Users", '#' %></li>
		          <li class="dropdown">
		            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
		              Account <b class="caret"></b>
		            </a>
		            <ul class="dropdown-menu">
		              <li><%= link_to "Profile", current_user %></li>
		              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
		              <li class="divider"></li>
		              <li>
		                <%= link_to "Log out", logout_path, method: "delete" %>
		              </li>
		            </ul>
		          </li>
		        <% else %>
		          <li><%= link_to "Log in", login_path %></li>
		        	<li><%= link_to "Sign Up", signup_path %></li>
		        <% end %>
			</ul>
	</div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookLand | <%= yield :title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>

	<%= render 'layouts/header' %>

<div class="container white_box">
	<% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<div class="center jumbotron">
	<h1>Welcome at BoolLand</h1>
	<p>Here you can find what to read</p>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit User") %>
<h1>Updating Your profile</h1>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
   </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
	<div class="col-md-6" "col-md-offset-3">
		<%= form_for(@user) do |f| %>
		 <%= render 'shared/error_messages' %>

	      <%= f.label :name %>
	      <%= f.text_field :name, class: 'form-control' %>

	      <%= f.label :email %>
	      <%= f.email_field :email, class: 'form-control' %>

	      <%= f.label :password %>
	      <%= f.password_field :password, class: 'form-control' %>

	      <%= f.label :password_confirmation, "Confirmation" %>
	      <%= f.password_field :password_confirmation, class: 'form-control' %>


		<%= f.submit "Create my accout", class:"btn btn-primary" %>

		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<p><%= @user.name %>, <%= @user.email %></p>